/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.sheridancollege.week3.softwarefundamentals.ice1;
import java.util.Scanner;
/**
 * A class that fills a magic hand of 7 cards with random Card Objects
 * and then asks the user to pick a card and searches the array of cards
 * for the match to the user's card. To be used as starting code in ICE 1
 * @author dancye
 * @modifier Abdulrahman Khan (monamoe) 01.02.2018
 */
public class CardTrick {
    public static void main(String[] args)
    {
        Scanner dataIn = new Scanner(System.in);
        
        //7 random cards created by the program
        Card[] magicHand = new Card[7];
        //assigns values to the random 7
        for (int i=0; i<magicHand.length; i++)
        {
            magicHand[i] = new Card();
            magicHand[i].setValue();
            magicHand[i].setSuit();
        }
        
        
        //insert code to ask the user for Card value and suit, create their card
        System.out.print("Please enter a Suite. (Hearts, Diamonds, Spades, Clubs)  : ");
        String userSuit = dataIn.nextLine();
        System.out.print("Please enter a Card Number : ");
        int userNumber = dataIn.nextInt();
        System.out.println();
        
        //a variable that changes its value to 0 when the user guessest he correct answer
        int correctAnswer = 1;
        // and search magicHand here
        for (int i=0; i<magicHand.length; i++){
            //checks if the user's input matches any of the cards generated by the user
            if(userSuit == magicHand[i].getSuit() && userNumber == magicHand[i].getValue()){
                System.out.println("You guessed the correct card! Card Number: " + i + " (" + userNumber + " of " + userSuit + ")");
                correctAnswer = 0;
            }
        }
        //if none of the values match, inform the user
        if(correctAnswer == 1)
            System.out.println("Your input did not match any of the cards generated by the program.");
    }
    
}
